development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: gkgk
  database: swell_media_dev

test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: gkgk
  database: swell_media_test
